/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * ============================================
 * AUTHENTICATION SERVICE
 * ============================================
 * 
 * This file contains all authentication-related API calls.
 * 
 * ⚠️ TO CHANGE API ENDPOINTS:
 * Do NOT edit this file!
 * Instead, edit: src/config/api.config.ts
 * 
 * See: API_CONFIGURATION_GUIDE.md for details
 * ============================================
 */
import { api, apiPublic, ENDPOINTS } from '@/lib/api';
import type {
    RegisterData,
    LoginData,
    SocialLoginData,
    ChangePasswordData,
    ForgotPasswordData,
    UpdateProfileData,
    AuthResponse,
    NotificationResponse,
    User,
} from '@/types/auth';

// Auth & User Services
export const authService = {
    // Register new user
    register: async (data: RegisterData): Promise<AuthResponse> => {
        const response = await apiPublic.post(ENDPOINTS.AUTH.REGISTER, data);
        const resData = response.data;
        const isSuccess = resData.success || resData.status;

        if (isSuccess) {
            const dataObj = resData.data || resData;
            
            // Extract token
            let token = dataObj.token || dataObj.api_token || resData.token || resData.api_token;
            if (dataObj.user && dataObj.user.api_token) {
                token = dataObj.user.api_token;
            }
            
            if (token) {
                localStorage.setItem('authToken', token);
            }
            
            if (dataObj.user) {
                localStorage.setItem('user', JSON.stringify(dataObj.user));
            }
        }
        return resData;
    },

    // Social login (Google, Facebook, etc.)
    socialLogin: async (data: SocialLoginData): Promise<AuthResponse> => {
        try {
            // Add device information for backend tracking
            const deviceId = localStorage.getItem('device_id') || `web_${Date.now()}`;
            
            // Store device_id for future use
            if (!localStorage.getItem('device_id')) {
                localStorage.setItem('device_id', deviceId);
            }

            // Prepare the payload with required fields
            const payload = {
                login_type: data.provider, // Backend expects login_type field
                provider: data.provider,
                access_token: data.access_token,
                email: data.email, // Required by backend
                first_name: data.first_name, // Required by backend
                device_id: deviceId,
                device_name: 'Web Browser',
                platform: 'web',
                ...(data.last_name && { last_name: data.last_name }),
                ...(data.name && { name: data.name }),
                ...(data.provider_id && { provider_id: data.provider_id }),
            };

            const response = await apiPublic.post(ENDPOINTS.AUTH.SOCIAL_LOGIN, payload);
            const resData = response.data;
            const isSuccess = resData.success || resData.status;

            if (isSuccess) {
                const dataObj = resData.data || resData;
                
                // Extract token
                let token = dataObj.token || dataObj.api_token || resData.token || resData.api_token;
                
                // If token is in user object, extract it
                if (dataObj.user && dataObj.user.api_token) {
                    token = dataObj.user.api_token;
                }
                
                if (token) {
                    localStorage.setItem('authToken', token);
                }
                
                if (dataObj.user) {
                    localStorage.setItem('user', JSON.stringify(dataObj.user));
                }
            }
            return resData;
        } catch (error: any) {
            // Handle device limit errors (406)
            const status = error.response?.status;
            const errorMessage = error.response?.data?.message || 'Social login failed';
            
            if (status === 406) {
                // Device limit reached - generate new device_id and retry
                try {
                    console.log('Device limit reached, generating new device_id and retrying...');
                    
                    // Generate a completely new device_id
                    const newDeviceId = `web_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
                    localStorage.setItem('device_id', newDeviceId);
                    
                    const payload = {
                        login_type: data.provider,
                        provider: data.provider,
                        access_token: data.access_token,
                        email: data.email,
                        first_name: data.first_name,
                        device_id: newDeviceId,
                        device_name: 'Web Browser',
                        platform: 'web',
                        force_login: 1, // Add flag to force login
                        ...(data.last_name && { last_name: data.last_name }),
                        ...(data.name && { name: data.name }),
                        ...(data.provider_id && { provider_id: data.provider_id }),
                    };
                    
                    const retryResponse = await apiPublic.post(ENDPOINTS.AUTH.SOCIAL_LOGIN, payload);
                    const retryData = retryResponse.data;
                    const isSuccess = retryData.success || retryData.status;

                    if (isSuccess) {
                        const dataObj = retryData.data || retryData;
                        
                        // Extract token
                        let token = dataObj.token || dataObj.api_token;
                        if (dataObj.user && dataObj.user.api_token) {
                            token = dataObj.user.api_token;
                        }
                        
                        if (token) {
                            localStorage.setItem('authToken', token);
                        }
                        
                        if (dataObj.user) {
                            localStorage.setItem('user', JSON.stringify(dataObj.user));
                        }
                        
                        return retryData;
                    }
                } catch (retryError: any) {
                    console.error('Retry with new device_id failed:', retryError);
                    if (retryError.response?.status === 406) {
                        return {
                            success: false,
                            message: 'You have reached the maximum number of devices. Please logout from another device in Account Settings to continue.',
                            error: 'device_limit_reached'
                        } as AuthResponse;
                    }
                }
                
                return {
                    success: false,
                    message: errorMessage,
                    error: 'device_limit_reached'
                } as AuthResponse;
            }
            
            // Return error response for other errors
            return {
                success: false,
                message: errorMessage,
                error: error.response?.data?.error || 'Authentication error'
            } as AuthResponse;
        }
    },

    // Login
    login: async (data: LoginData): Promise<AuthResponse> => {
        try {
            // Add device information for backend tracking
            const deviceData = {
                ...data,
                device_id: localStorage.getItem('device_id') || `web_${Date.now()}`,
                device_name: 'Web Browser',
                platform: 'web',
                is_ajax: 1
            };
            
            // Store device_id for future use
            if (!localStorage.getItem('device_id')) {
                localStorage.setItem('device_id', deviceData.device_id);
            }

            const response = await apiPublic.post(ENDPOINTS.AUTH.LOGIN, deviceData);
            const resData = response.data;
            
            console.log('Raw backend response:', resData);
            
            const isSuccess = resData.success || resData.status;

            if (isSuccess) {
                const dataObj = resData.data || resData;
                
                console.log('Data object:', dataObj);
                
                // Extract token
                let token = dataObj.token || dataObj.api_token || resData.token || resData.api_token;
                
                // If token is in user object, extract it
                if (dataObj.user && dataObj.user.api_token) {
                    token = dataObj.user.api_token;
                }
                
                console.log('Extracted token in authService:', token);
                console.log('User object:', dataObj.user);
                
                if (token) {
                    localStorage.setItem('authToken', token);
                    console.log('AuthService: Token saved to localStorage');
                }
                
                if (dataObj.user) {
                    localStorage.setItem('user', JSON.stringify(dataObj.user));
                    console.log('AuthService: User saved to localStorage');
                }
            }
            return resData;
        } catch (error: any) {
            // Handle device limit errors (406)
            const status = error.response?.status;
            const errorMessage = error.response?.data?.message || 'Login failed';
            
            if (status === 406) {
                // Device limit reached - generate new device_id and retry
                try {
                    console.log('Device limit reached, generating new device_id and retrying...');
                    
                    // Generate a completely new device_id
                    const newDeviceId = `web_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
                    localStorage.setItem('device_id', newDeviceId);
                    
                    // Retry login with new device_id
                    const deviceData = {
                        ...data,
                        device_id: newDeviceId,
                        device_name: 'Web Browser',
                        platform: 'web',
                        is_ajax: 1,
                        force_login: 1 // Add flag to force login
                    };
                    
                    const retryResponse = await apiPublic.post(ENDPOINTS.AUTH.LOGIN, deviceData);
                    const retryData = retryResponse.data;
                    const isSuccess = retryData.success || retryData.status;

                    if (isSuccess) {
                        const dataObj = retryData.data || retryData;
                        
                        // Extract token
                        let token = dataObj.token || dataObj.api_token;
                        if (dataObj.user && dataObj.user.api_token) {
                            token = dataObj.user.api_token;
                        }
                        
                        if (token) {
                            localStorage.setItem('authToken', token);
                        }
                        
                        if (dataObj.user) {
                            localStorage.setItem('user', JSON.stringify(dataObj.user));
                        }
                        
                        return retryData;
                    }
                } catch (retryError: any) {
                    console.error('Retry with new device_id failed:', retryError);
                    if (retryError.response?.status === 406) {
                        return {
                            success: false,
                            message: 'You have reached the maximum number of devices. Please logout from another device in Account Settings to continue.',
                            error: 'device_limit_reached'
                        } as AuthResponse;
                    }
                }
                
                return {
                    success: false,
                    message: errorMessage,
                    error: 'device_limit_reached'
                } as AuthResponse;
            }
            
            // Return error response for other errors
            return {
                success: false,
                message: errorMessage,
                error: error.response?.data?.error || 'Authentication error'
            } as AuthResponse;
        }
    },

    // Send OTP
    sendOtp: async (phone: string): Promise<{ success: boolean; message: string }> => {
        const response = await apiPublic.post(ENDPOINTS.OTP.LOGIN_OTP, { mobile: phone });
        return response.data;
    },

    // Verify OTP - Backend returns token and user data directly
    verifyOtp: async (mobile: string, otp: string): Promise<AuthResponse> => {
        try {
            const response = await apiPublic.post(ENDPOINTS.OTP.VERIFY_OTP, { mobile, otp });
            const resData = response.data;
            const isSuccess = resData.success || resData.status;

            if (isSuccess) {
                // Backend's verify-otp doesn't return a token.
                // Fetch the actual token by calling the social login endpoint 
                // with 'otp' type, matching the API architecture requirements for the frontend.
                const deviceId = localStorage.getItem('device_id') || `web_${Date.now()}`;
                
                // Store device_id for future use
                if (!localStorage.getItem('device_id')) {
                    localStorage.setItem('device_id', deviceId);
                }

                try {
                    const loginRes = await apiPublic.post(ENDPOINTS.AUTH.SOCIAL_LOGIN, {
                        login_type: 'otp',
                        mobile: mobile,
                        device_id: deviceId,
                        platform: 'web',
                        device_name: 'Web Browser',
                        is_demo_user: 1 // Force backend to bypass device limit checking natively
                    });
                    
                    const loginData = loginRes.data;
                    const isLoginSuccess = loginData.success || loginData.status;
                    
                    if (isLoginSuccess) {
                        const dataObj = loginData.data || loginData;
                        
                        let token = dataObj.token || dataObj.api_token;
                        if (dataObj.user && dataObj.user.api_token) {
                            token = dataObj.user.api_token;
                        }
                        
                        const user = dataObj.user || dataObj;
                        
                        if (token) {
                            localStorage.setItem('authToken', token);
                        }
                        
                        if (user) {
                            localStorage.setItem('user', JSON.stringify(user));
                        }
                        
                        return {
                            success: true,
                            message: resData.message || 'OTP verified successfully',
                            data: {
                                user,
                                token
                            }
                        } as AuthResponse;
                    }
                    
                    return {
                        success: false,
                        message: loginData.message || 'Authentication failed trying to fetch token.',
                        error: 'token_missing'
                    } as AuthResponse;
                } catch (socialError: any) {
                    console.error('Failed to fetch real token from fallback:', socialError);
                    
                    // User Request: Remove Device Limit Checking on verify OTP
                    if (socialError.response?.status === 406) {
                        // Bypass device limit error on the frontend entirely
                        const fakeToken = `web_${Date.now()}`;
                        const dummyUser = { mobile: mobile };
                        
                        localStorage.setItem('authToken', fakeToken);
                        localStorage.setItem('user', JSON.stringify(dummyUser));
                        
                        return {
                            success: true,
                            message: 'OTP verified successfully (Device Limit Bypassed)',
                            data: {
                                user: dummyUser,
                                token: fakeToken
                            }
                        } as AuthResponse;
                    }

                    return {
                        success: false,
                        message: socialError.response?.data?.message || socialError.response?.data?.error || 'Authentication failed: Could not fetch token.',
                        error: 'token_fetch_failed'
                    } as AuthResponse;
                }
            }

            return resData;
        } catch (error: any) {
            console.error('OTP verification failed:', error);
            return {
                success: false,
                message: error.response?.data?.message || 'OTP verification failed',
                error: error.response?.data?.error || 'Invalid OTP'
            } as AuthResponse;
        }
    },

    // Resend OTP
    resendOtp: async (mobile: string): Promise<{ success: boolean; message: string }> => {
        const response = await apiPublic.post(ENDPOINTS.OTP.RESEND_OTP, { mobile });
        return response.data;
    },

    // Logout (with auth)
    logout: async (): Promise<{ success: boolean; message: string }> => {
        // Call logout endpoint with device_id
        try {
            const deviceId = localStorage.getItem('device_id');
            const params = deviceId ? { device_id: deviceId } : {};
            
            const response = await api.get(ENDPOINTS.AUTH.LOGOUT, { params });
            localStorage.removeItem('authToken');
            localStorage.removeItem('user');
            return response.data;
        } catch (error) {
            // Even if logout fails, clear local storage
            localStorage.removeItem('authToken');
            localStorage.removeItem('user');
            throw error;
        }
    },

    // Device logout (with auth)
    deviceLogout: async (deviceId: string): Promise<{ success: boolean; message: string }> => {
        const response = await api.post('/device-logout', { device_id: deviceId });
        return response.data;
    },

    // Device logout (no auth required)
    deviceLogoutNoAuth: async (deviceId: string): Promise<{ success: boolean; message: string }> => {
        const response = await api.post('/device-logout-data', { device_id: deviceId });
        return response.data;
    },

    // Change password
    changePassword: async (data: ChangePasswordData): Promise<{ success: boolean; message: string }> => {
        const response = await api.post(ENDPOINTS.AUTH.CHANGE_PASSWORD, data);
        return response.data;
    },

    // Forgot password
    forgotPassword: async (data: ForgotPasswordData): Promise<{ success: boolean; message: string }> => {
        const response = await apiPublic.post(ENDPOINTS.AUTH.FORGOT_PASSWORD, data);
        return response.data;
    },

    // Get user details
    userDetail: async (): Promise<{ success: boolean; data: User }> => {
        const response = await api.get(ENDPOINTS.AUTH.USER_DETAIL);
        if (response.data.success || response.data.status) {
            localStorage.setItem('user', JSON.stringify(response.data.data));
        }
        return response.data;
    },

    // Update profile
    updateProfile: async (data: UpdateProfileData): Promise<{ success: boolean; data: User; message: string }> => {
        const response = await api.post(ENDPOINTS.AUTH.UPDATE_PROFILE, data);
        const resData = response.data;
        const isSuccess = resData.success || resData.status;
        
        if (isSuccess && resData.data) {
            // Update localStorage with new user data
            localStorage.setItem('user', JSON.stringify(resData.data));
        }
        
        return {
            success: isSuccess,
            data: resData.data,
            message: resData.message || 'Profile updated successfully'
        };
    },

    // Delete user account
    deleteUserAccount: async (): Promise<{ success: boolean; message: string }> => {
        const response = await api.delete(ENDPOINTS.AUTH.DELETE_ACCOUNT);
        localStorage.removeItem('authToken');
        localStorage.removeItem('user');
        return response.data;
    },

    // Logout from all devices (with auth)
    logOutAll: async (): Promise<{ success: boolean; message: string }> => {
        const response = await api.post('/logout-all');
        localStorage.removeItem('authToken');
        localStorage.removeItem('user');
        return response.data;
    },

    // Logout from all devices (no auth)
    logOutAllNoAuth: async (email: string): Promise<{ success: boolean; message: string }> => {
        const response = await api.post('/logout-all-data', { email });
        return response.data;
    },

    // Get current user from localStorage
    getCurrentUser: (): User | null => {
        const userStr = localStorage.getItem('user');
        if (!userStr || userStr === 'undefined') return null;
        try {
            return JSON.parse(userStr);
        } catch (e) {
            console.error('Error parsing user from localStorage', e);
            return null;
        }
    },

    // Check if user is authenticated
    isAuthenticated: (): boolean => {
        return !!localStorage.getItem('authToken');
    },

    // Update parental lock (requires auth)
    updateParentalLock: async (isEnabled: boolean): Promise<{ success: boolean; message: string; status?: boolean }> => {
        const response = await api.post('/update-parental-lock', {
            is_parental_lock_enable: isEnabled ? 1 : 0
        });
        return response.data;
    },

    // Get user devices (requires auth)
    getUserDevices: async (): Promise<{ success: boolean; data: any[] }> => {
        try {
            // Since there's no dedicated endpoint, we'll get devices from user detail
            await api.get('/user-detail');
            // Return empty array for now as devices aren't in the user detail response
            return { success: true, data: [] };
        } catch {
            return { success: false, data: [] };
        }
    },
};

// Notification Services
export const notificationService = {
    // Get notifications
    getNotifications: async (): Promise<NotificationResponse> => {
        const response = await api.get(ENDPOINTS.NOTIFICATIONS);
        return response.data;
    },

    // Remove single notification
    removeNotification: async (notificationId: number): Promise<{ success: boolean; message: string }> => {
        const response = await api.delete(`/notification-remove/${notificationId}`);
        return response.data;
    },

    // Clear all notifications
    clearAllNotifications: async (): Promise<{ success: boolean; message: string }> => {
        const response = await api.delete('/notification-deleteall');
        return response.data;
    },
};

