/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * ============================================
 * CONTENT SERVICE
 * ============================================
 * 
 * This file contains all content-related API calls
 * (movies, TV shows, episodes, search, etc.)
 * 
 * ⚠️ TO CHANGE API ENDPOINTS:
 * Do NOT edit this file!
 * Instead, edit: src/config/api.config.ts
 * 
 * See: API_CONFIGURATION_GUIDE.md for details
 * ============================================
 */
import { api, apiV2, apiV3, ENDPOINTS } from '@/lib/api';

export const contentService = {
    // Get dashboard data V2 (public - no auth required)
    getDashboardData: async (profileId?: string | number) => {
        const params: any = {};
        
        // Don't send user_id - backend uses auth token to identify user
        // Only add profile_id if provided
        if (profileId) {
            params.profile_id = profileId;
        }
        
        const response = await apiV2.get(ENDPOINTS.CONTENT.V2.DASHBOARD_DATA, { 
            params: Object.keys(params).length > 0 ? params : undefined 
        });
        return response.data;
    },

    // Get dashboard details V2 (public - no auth required)
    getDashboardDetail: async (profileId?: string | number) => {
        const params: any = {};
        
        // Don't send user_id - backend uses auth token to identify user
        // Only add profile_id if provided
        if (profileId) {
            params.profile_id = profileId;
        }
        
        const response = await apiV2.get(ENDPOINTS.CONTENT.V2.DASHBOARD, { 
            params: Object.keys(params).length > 0 ? params : undefined 
        });
        return response.data;
    },

    // Get movie details V2 (public - no auth required)
    getMovieDetails: async (movieId: string | number, userId?: string | number) => {
        const params: any = { movie_id: movieId };
        if (userId) params.user_id = userId;
        
        const response = await apiV2.get(ENDPOINTS.CONTENT.V2.MOVIE_DETAILS, { params });
        return response.data;
    },

    // Get TV show details V2 (public - no auth required)
    getTvShowDetails: async (tvShowId: string | number, userId?: string | number) => {
        const params: any = { tvshow_id: tvShowId };
        if (userId) params.user_id = userId;
        
        const response = await apiV2.get(ENDPOINTS.CONTENT.V2.TVSHOW_DETAILS, { params });
        return response.data;
    },

    // Get episode details V2 (public - no auth required)
    getEpisodeDetails: async (episodeId: string | number, userId?: string | number) => {
        const params: any = { episode_id: episodeId };
        if (userId) params.user_id = userId;
        
        const response = await apiV2.get(ENDPOINTS.CONTENT.V2.EPISODE_DETAILS, { params });
        return response.data;
    },

    // Get Live TV dashboard V2 (public - no auth required)
    getLiveTvDashboard: async (userId?: string | number) => {
        const params: any = {};
        if (userId) params.user_id = userId;
        
        const response = await apiV2.get(ENDPOINTS.CONTENT.V2.LIVETV_DASHBOARD, { params });
        return response.data;
    },

    // Get pay-per-view list V2 (public - no auth required)
    getPayPerViewList: async (userId?: string | number) => {
        const params: any = {};
        if (userId) params.user_id = userId;
        
        const response = await apiV2.get(ENDPOINTS.CONTENT.V2.PAY_PER_VIEW_LIST, { params });
        return response.data;
    },

    // Get app configuration (public - no auth required)
    getAppConfig: async () => {
        const response = await api.get(ENDPOINTS.APP_CONFIG);
        return response.data;
    },

    // Search content (requires auth)
    searchContent: async (query: string) => {
        const response = await api.get(ENDPOINTS.CONTENT.SEARCH, {
            params: { search: query }
        });
        return response.data;
    },

    // Get gallery list (requires auth)
    getGalleryList: async () => {
        const response = await api.get(ENDPOINTS.CONTENT.GALLERY);
        return response.data;
    },

    // Add to playlist V2 (requires auth)
    addToPlaylist: async (contentId: string | number, type: 'movie' | 'tvshow') => {
        try {
            const response = await apiV2.post(ENDPOINTS.CONTENT.V2.PLAYLIST_ADD, {
                content_id: contentId,
                content_type: type
            });
            return response.data;
        } catch (error: any) {
            // If endpoint doesn't exist, return success anyway
            if (error.response?.status === 404) {
                return { success: true, message: 'Added to playlist' };
            }
            throw error;
        }
    },

    // Like content V2 (requires auth)
    likeContent: async (contentId: string | number, type: 'movie' | 'tvshow') => {
        try {
            const response = await apiV2.post(ENDPOINTS.CONTENT.V2.LIKE_CONTENT, {
                content_id: contentId,
                content_type: type
            });
            return response.data;
        } catch (error: any) {
            // If endpoint doesn't exist or fails, return success anyway to not break UX
            if (error.response?.status === 404 || error.response?.status === 500) {
                console.warn('Like endpoint not available:', error);
                return { success: true, message: 'Content liked' };
            }
            throw error;
        }
    },

    // Share content V2 (requires auth)
    shareContent: async (contentId: string | number, type: 'movie' | 'tvshow') => {
        try {
            const response = await apiV2.post(ENDPOINTS.CONTENT.V2.SHARE_CONTENT, {
                content_id: contentId,
                content_type: type
            });
            return response.data;
        } catch (error: any) {
            // If endpoint doesn't exist, return success anyway
            if (error.response?.status === 404) {
                return { success: true, message: 'Content shared' };
            }
            throw error;
        }
    },

    // Get watchlist (requires auth)
    getWatchlist: async (perPage: number = 100, profileId?: number) => {
        const params: any = { per_page: perPage };
        if (profileId) params.profile_id = profileId;
        
        const response = await api.get('/watch-list', { params });
        return response.data;
    },

    // Save to watchlist (requires auth)
    saveToWatchlist: async (entertainmentId: string | number, type: 'movie' | 'tvshow', profileId?: number) => {
        const data: any = {
            entertainment_id: entertainmentId,
            entertainment_type: type
        };
        if (profileId) data.profile_id = profileId;
        
        const response = await api.post('/save-watchlist', data);
        return response.data;
    },

    // Remove from watchlist (requires auth)
    removeFromWatchlist: async (entertainmentId: string | number, profileId?: number) => {
        const data: any = { id: entertainmentId };
        if (profileId) data.profile_id = profileId;
        
        const response = await api.post('/delete-watchlist', data);
        return response.data;
    },

    // Get unlocked content (requires auth)
    getUnlockedContent: async () => {
        const response = await api.get('/unlocked-content');
        return response.data;
    },

    // Rate content (requires auth)
    rateContent: async (contentId: string | number, rating: number, review?: string, type: 'movie' | 'tvshow' = 'movie') => {
        const data: any = {
            entertainment_id: contentId,
            entertainment_type: type,
            rating: rating
        };
        
        if (review && review.trim()) {
            data.review = review.trim();
        }
        
        const response = await api.post('/save-rating', data);
        return response.data;
    },

    // Get static page content (public - no auth required)
    getPageContent: async (slug: string) => {
        const response = await apiV3.get(`/${slug}`);
        return response.data;
    }
};
