/**
 * ============================================
 * SUBSCRIPTION SERVICE
 * ============================================
 * 
 * This file contains all subscription and payment-related API calls.
 * 
 * ⚠️ TO CHANGE API ENDPOINTS:
 * Do NOT edit this file!
 * Instead, edit: src/config/api.config.ts
 * 
 * See: API_CONFIGURATION_GUIDE.md for details
 * ============================================
 */
import { api, apiPublic, ENDPOINTS } from '@/lib/api';

interface PlanLimitation {
    id: number;
    limitation_name: string;
    limitation_slug: string;
    limit: string | { value: string } | any; // Can be string, object with value, or other types
    planlimitation_id?: number;
    limitation_title?: string;
    limitation_value?: boolean;
    message?: string; // Descriptive message from backend
    slug?: string;
    status?: number;
}

interface Plan {
    plan_id: number;
    name: string;
    identifier: string;
    price: number;
    discount: number;
    discount_percentage: number;
    total_price: number;
    level: number;
    duration: number;
    duration_value: string;
    description: string;
    plan_type: PlanLimitation[];
    status: number;
}

interface SubscriptionStatus {
    id: number;
    is_subscription_enabled: boolean;
}

interface SubscriptionHistory {
    id: number;
    name: string; // From backend JSON
    plan_name?: string; // Fallback
    plan_id?: number;
    amount: number;
    discount_percentage?: number;
    discount_amount?: number;
    coupon_discount?: number;
    tax_amount?: number;
    total_amount?: number;
    type: string; // From backend JSON (e.g., 'month')
    duration?: number;
    duration_value?: string;
    level?: number;
    identifier?: string;
    plan_type?: string; // JSON string from backend
    start_date: string;
    end_date: string;
    status: string;
    payment_method?: string;
    payment_id?: number;
    transaction_id?: string;
    device_id?: string;
    invoice_url?: string;
}

export const subscriptionService = {
    // Get subscription status (public - no auth required)
    getSubscriptionStatus: async (): Promise<SubscriptionStatus> => {
        const response = await apiPublic.get(ENDPOINTS.SUBSCRIPTION);
        return response.data;
    },

    // Get plan list (public - no auth required)
    getPlanList: async (perPage: number = 100): Promise<{ status: boolean; data: Plan[]; message: string }> => {
        const response = await apiPublic.get('/plan-list', {
            params: { per_page: perPage }
        });
        return response.data;
    },

    // Get all plans (public - no auth required)
    getAllPlans: async (): Promise<{ status: boolean; data: Plan[]; message: string }> => {
        const response = await apiPublic.get('/plans');
        return response.data;
    },

    // Get single plan details (public - no auth required)
    getPlanDetails: async (planId: number): Promise<{ status: boolean; data: Plan; message: string }> => {
        const response = await apiPublic.get(`/plans/${planId}`);
        return response.data;
    },

    // Save subscription details (requires auth)
    saveSubscription: async (data: {
        plan_id: number;
        payment_method?: string;
        payment_type?: string;
        payment_status?: string;
        transaction_id?: string;
        device_id?: number;
    }): Promise<{ success: boolean; message: string; data?: any }> => {
        const response = await api.post('/save-subscription-details', data);
        return response.data;
    },

    // Get user subscription history (requires auth)
    getSubscriptionHistory: async (): Promise<{ success?: boolean; status?: boolean; data: SubscriptionHistory[]; message: string }> => {
        const response = await api.get('/user-subscription_histroy'); // Note: Backend has typo 'histroy'
        return response.data;
    },

    // Cancel subscription (requires auth)
    cancelSubscription: async (subscriptionId: number): Promise<{ success: boolean; message: string }> => {
        const response = await api.post('/cancle-subscription', { // Note: Backend has typo 'cancle'
            subscription_id: subscriptionId
        });
        return response.data;
    },

    // Create Razorpay order (public - for payment)
    createRazorpayOrder: async (data: {
        amount: number;
        currency: string;
        mobile: string;
        email: string;
        name: string;
    }): Promise<any> => {
        const response = await apiPublic.post(ENDPOINTS.RAZORPAY.CREATE_ORDER, data);
        return response.data;
    },

    // Check if user has active subscription (requires auth)
    checkUserSubscription: async (): Promise<{ 
        hasActiveSubscription: boolean; 
        subscription?: any;
        message?: string;
    }> => {
        try {
            const response = await api.get('/user-subscription_histroy');
            
            if (response.data.status && response.data.data) {
                const subscriptions = response.data.data;
                
                // Check if user has any active subscription
                // The backend uses 'active' status. We check case-insensitively just in case.
                const activeSubscription = subscriptions.find((sub: any) => 
                    sub.status?.toLowerCase() === 'active'
                );
                
                return {
                    hasActiveSubscription: !!activeSubscription,
                    subscription: activeSubscription,
                    message: response.data.message
                };
            }
            
            return {
                hasActiveSubscription: false,
                message: 'No subscription found'
            };
        } catch (error) {
            console.error('Error checking subscription:', error);
            return {
                hasActiveSubscription: false,
                message: 'Failed to check subscription status'
            };
        }
    },
};
